stages:
  - test

before_script:
  - if command -v apt-get > /dev/null 2>&1; then apt-get update && apt-get -y install curl make; fi
  - curl https://codeload.github.com/sstephenson/bats/tar.gz/v0.4.0 > bats.tar.gz;
  - tar xvzf bats.tar.gz
  - mv bats-0.4.0 bats
  - export PATH=$PATH:bats/bin

.job_template: &job_definition
  stage: test
  script:
    - make test
#
# Ubuntu
#

"14.04 Trusty LTS":
  <<: *job_definition
  image: ubuntu:trusty

# This locale setup catched the bug that led to v1.0.1
"14.04 Trusty LTS UTF-8":
  <<: *job_definition
  image: ubuntu:trusty
  variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
  script:
    - bash
    - make test

"16.04 Xenial":
  <<: *job_definition
  image: ubuntu:xenial

"18.04 Bionic":
  <<: *job_definition
  image: ubuntu:bionic

"18.10 Cosmic":
  <<: *job_definition
  image: ubuntu:cosmic


